# Generated by Django 2.2.5 on 2019-11-28 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(default='', max_length=100)),
                ('Address', models.CharField(default='', max_length=100)),
                ('Occupation', models.CharField(default='', max_length=100)),
                ('Salary', models.IntegerField(default=0)),
                ('Phone', models.IntegerField(default=0)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
